CREATE TABLE GERACAO (
    ID INT PRIMARY KEY IDENTITY(1,1),
    DATA_GERAL DATE,
    DATA_INICIO DATE,
    DATA_FIM DATE
);

create table TIME  (
ID INT PRIMARY KEY IDENTITY(1,1),
NOME NVARCHAR(100) NOT NULL,
FOTO VARBINARY(MAX) NOT NULL,
)

ALTER TABLE COLABORADOR ADD TIME INT NOT NULL
select * from GERACAO_TIME

CREATE TABLE GERACAO_TIME(
ID INT PRIMARY KEY IDENTITY(1,1),
GERACAO INT NOT NULL,
TIME INT NOT NULL,
CONCLUSAO_CARD int,
SP_ENTREGUE int,
BACKLOG_TOTAL int,
BACKLOG_NOVO int,
WIP int,
BUG int,
LEADTIME int,
CICLETIME int
);
ALTER TABLE GERACAO_TIME ADD CONSTRAINT FK_GERACAO_TIME_GERACAO FOREIGN KEY (GERACAO) REFERENCES GERACAO (Id) ON DELETE CASCADE;
 
DROP TABLE GERACAO_TIME
 
CREATE TABLE TIMES(
[ID PK]
NOME nvarchar(10) NOT NULL,
FOTO varbinary(MAX) NULL,
 
)
 
CREATE TABLE GERACAO_COLABORADOR(
[ID PK],
[GERACAO_TIME FK],
[COLABORADOR FK],
HE FLOAT,
ENGAJAMENTO FLOAT,
TEMPO_TRABALHADO FLOAT,
TEMPO_APROPRIADO FLOAT,
)
ALTER TABLE GERACAO_COLABORADOR ADD CONSTRAINT FK_GERACAO_COLABORADOR_GERACAO_TIME FOREIGN KEY (GERACAO_TIME) REFERENCES GERACAO_TIME (Id) ON DELETE CASCADE;
ALTER TABLE GERACAO_COLABORADOR ADD CONSTRAINT FK_GERACAO_COLABORADOR_COLABORADOR FOREIGN KEY (COLABORADOR) REFERENCES COLABORADOR (Id) ON DELETE CASCADE;
 
CREATE TABLE GERACAO_BOARD(
[ID PK],
[GERACAO FK]
[DADOS DO BOARD - ROGÉRIO MANDARÁ]
)
 
CREATE TABLE ATIVIDADES(
ID INT PRIMARY KEY IDENTITY(1,1),
[COLABORADOR FK],
[DADOS DA TABELA TMETRIC],
[CLASSIFICACAO],
)
ALTER TABLE ATIVIDADES ADD CONSTRAINT FK_ATIVIDADES_GERACAO_COLABORADOR FOREIGN KEY (GERACAO_COLABORADOR) REFERENCES GERACAO_COLABORADOR (Id) ON DELETE CASCADE;
 
CREATE TABLE ATIVIDADES_TAGS(
[ID PK],
[ATIVIDADES FK],
TAG NVARCHAR(100)
)
ALTER TABLE ATIVIDADES_TAGS ADD CONSTRAINT FK_ATIVIDADES_TAGS_ATIVIDADES FOREIGN KEY (ATIVIDADES) REFERENCES ATIVIDADES (Id) ON DELETE CASCADE;


CREATE TABLE MOVIDESK(
	ID						UNIQUEIDENTIFIER ROWGUIDCOL PRIMARY KEY,
    NUMERO					INT,
	PERIODO					UNIQUEIDENTIFIER NOT NULL,
    DATAABERTURA			DATETIME,
    DATAFECHAMENTO			DATETIME,
    DATAVENCIMENTO			DATETIME,
    ASSUNTO					NVARCHAR(255),
	PESSOA					NVARCHAR(255),
	INDICADORSLA            NVARCHAR(50),
    RESPONSAVEL				UNIQUEIDENTIFIER,
	RESPONSAVELCHAMADO		NVARCHAR(255),
    RESPONSAVELEQUIPE		NVARCHAR(255),
    SERVICO					NVARCHAR(255),
    STATUS					NVARCHAR(50),

	CONSTRAINT [FK_MOVIDESK_RESPONSAVEL_ID]	FOREIGN KEY (RESPONSAVEL) REFERENCES COLABORADOR(ID),
	CONSTRAINT [FK_MOVIDESK_PERIODO_ID]		FOREIGN KEY ([PERIODO]) REFERENCES [PERIODO] ([Id]) ON DELETE CASCADE,
    TIME					NVARCHAR(255),

)