USE [BI_SISTEMAS]
GO

/****** Object:  Table [dbo].[COLABORADOR]    Script Date: 28/03/2024 15:25:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PERIODO](
	[ID] [uniqueidentifier] ROWGUIDCOL  NOT NULL,
	[DATA] [datetime] NOT NULL,
	[DATAINICIO] [datetime] NOT NULL,
	[DATATERMINO] [datetime] NOT NULL,
 CONSTRAINT [PK_PERIODO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
) ON [PRIMARY] 
GO

ALTER TABLE [dbo].[PERIODO] ADD  CONSTRAINT [DF_PERIODO_ID]  DEFAULT (newid()) FOR [ID]
GO

CREATE TABLE [dbo].[COLABORADOR](
	[ID] [uniqueidentifier] ROWGUIDCOL  NOT NULL,
	[NOME] [nvarchar](255) NOT NULL,
	[CARGO] [nvarchar](255) NOT NULL,
	[FOTO] [varbinary](MAX) NULL,
	[CARGAHORARIA] [int] NULL,
	[INICIO] [datetime] NULL,
	[TERMINO] [datetime] NULL,
	[TIME] [nvarchar](100) NULL,
	[USER_TMETRIC] [nvarchar](255) NULL,
 CONSTRAINT [PK_COLABORADOR] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[COLABORADOR] ADD  CONSTRAINT [DF_COLABORADOR_ID]  DEFAULT (newid()) FOR [ID]
GO

CREATE TABLE [dbo].[TMETRIC](
	[ID] [uniqueidentifier] ROWGUIDCOL  NOT NULL,
	[PERIODO] [uniqueidentifier] NOT NULL,
	[DATA] [datetime] NOT NULL,
	[USUARIO] [nvarchar](255) NOT NULL,
	[INICIO] [datetime] NOT NULL,
	[TERMINO] [datetime] NOT NULL,
	[DURACAO] [datetime] NOT NULL,
	[DEVOPSTASK] [int] NULL,
	[COLABORADOR] [uniqueidentifier] NULL,
	[ATIVIDADE] [nvarchar](MAX) NOT NULL,
	[CARGA] [datetime] NOT NULL,
	[TIPO] [nvarchar] (100) NULL,
 CONSTRAINT [PK_TMETRIC] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
CONSTRAINT [FK_TMETRIC_COLABORADOR_ID] FOREIGN KEY ([COLABORADOR]) REFERENCES [COLABORADOR] ([Id]) ON DELETE CASCADE,
CONSTRAINT [FK_TMETRIC_PERIODO_ID] FOREIGN KEY ([PERIODO]) REFERENCES [PERIODO] ([Id]) ON DELETE CASCADE
) ON [PRIMARY] 
GO

ALTER TABLE [dbo].[TMETRIC] ADD  CONSTRAINT [DF_TMETRIC_ID]  DEFAULT (newid()) FOR [ID]
GO
ALTER TABLE TMETRIC 
ADD PARENT_TYPE INT NULL,PARENT_TITULO NVARCHAR(1000) NULL ;
--drop table [COLABORADOR]




CREATE TABLE [dbo].[PONTO](
	[ID] [uniqueidentifier] ROWGUIDCOL  NOT NULL,
	[PERIODO] [uniqueidentifier] NOT NULL,
	[HORAS] [datetime] NOT NULL,
	[COLABORADOR] [uniqueidentifier] NOT NULL,
	[TIPO] [INT] NOT NULL,
 CONSTRAINT [PK_PONTO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
CONSTRAINT [FK_PONTO_PERIODO_ID] FOREIGN KEY ([PERIODO]) REFERENCES [PERIODO] ([Id]) ON DELETE CASCADE,
CONSTRAINT [FK_PONTO_COLABORADOR_ID] FOREIGN KEY ([COLABORADOR]) REFERENCES [COLABORADOR] ([Id]) ON DELETE CASCADE
) ON [PRIMARY] 
GO

ALTER TABLE [dbo].[PONTO] ADD  CONSTRAINT [DF_PONTO_ID]  DEFAULT (newid()) FOR [ID]
GO